"""Boundaries for persisted terminal observations."""

MAX_OBSERVATION_JSON_BYTES: int = 16_384
MAX_OBSERVATION_ERROR_LENGTH: int = 2_000
HEARTBEAT_INTERVAL_SECONDS: float = 10.0
RUN_DISPLAY_COMMAND_ENV_VAR: str = "STREAMBUILD_RUN_DISPLAY_COMMAND"
RUN_INVOCATION_ID_ENV_VAR: str = "STREAMBUILD_RUN_INVOCATION_ID"
