"""Neutral adapter constants."""

REDACTED_SECRET_PLACEHOLDER: str = "***"
ADAPTER_DATABASE_PLACEHOLDER: str = "__streambuild_target_database__"
METADATA_OBJECT_STATE_TABLE_NAME: str = "_streambuild_virtual_object_state"
METADATA_DEPLOYMENTS_TABLE_NAME: str = "_streambuild_virtual_deployments"
METADATA_DEPLOYMENT_WATERMARKS_TABLE_NAME: str = "_streambuild_virtual_replay_boundaries"
METADATA_PUBLISH_HISTORY_TABLE_NAME: str = "_streambuild_virtual_publications"
METADATA_PUBLISH_OPERATION_COLUMN_NAME: str = "operation"
METADATA_PUBLISH_PREVIOUS_DEPLOYMENT_COLUMN_NAME: str = "previous_deployment_id"
METADATA_SCHEMA_VERSIONS_TABLE_NAME: str = "_streambuild_schema_versions"
METADATA_DIRECT_FINGERPRINTS_TABLE_NAME: str = "_streambuild_direct_fingerprints"
METADATA_MANIFESTS_TABLE_NAME: str = "_streambuild_manifests"
METADATA_INVOCATIONS_TABLE_NAME: str = "_streambuild_invocations"
METADATA_NODE_RESULTS_TABLE_NAME: str = "_streambuild_node_results"
METADATA_RUN_EVENTS_TABLE_NAME: str = "_streambuild_run_events"
METADATA_RUN_STATEMENTS_TABLE_NAME: str = "_streambuild_run_statements"
METADATA_SENSOR_CHECKPOINTS_TABLE_NAME: str = "_streambuild_sensor_checkpoints"
METADATA_SENSOR_TICKS_TABLE_NAME: str = "_streambuild_sensor_ticks"
METADATA_SENSOR_STEPS_TABLE_NAME: str = "_streambuild_sensor_steps"
METADATA_SENSOR_OVERRIDES_TABLE_NAME: str = "_streambuild_sensor_overrides"
METADATA_SENSOR_LEASES_TABLE_NAME: str = "_streambuild_sensor_leases"
TARGET_MUTATION_LOCK_TABLE_NAME: str = "_streambuild_target_mutation_lock"
VIRTUAL_OBJECT_STATE_KIND_DEPLOYMENT: str = "deployment"
VIRTUAL_OBJECT_STATE_KIND_RECONCILE: str = "reconcile"
VIRTUAL_DEPLOYMENT_STATUS_INCOMPLETE: str = "incomplete"
REPLAY_VALUE_KIND_INTEGER: str = "integer"
REPLAY_VALUE_KIND_TIMESTAMP: str = "timestamp"
MANAGED_SOURCE_KIND_KAFKA: str = "kafka"
ADAPTER_SECRET_PLACEHOLDER_PREFIX: str = "__streambuild_secret__"
ADAPTER_SECRET_PLACEHOLDER_SUFFIX: str = "__"

REFRESHABLE_VIEW_SETTING: str = "allow_experimental_refreshable_materialized_view = 1"
