"""Neutral adapter constants."""

REDACTED_SECRET_PLACEHOLDER: str = "***"
ADAPTER_DATABASE_PLACEHOLDER: str = "__streambuild_target_database__"
METADATA_OBJECT_STATE_TABLE_NAME: str = "_streambuild_virtual_object_state"
METADATA_DEPLOYMENTS_TABLE_NAME: str = "_streambuild_virtual_deployments"
METADATA_DEPLOYMENT_WATERMARKS_TABLE_NAME: str = "_streambuild_virtual_replay_boundaries"
METADATA_PUBLISH_HISTORY_TABLE_NAME: str = "_streambuild_virtual_publications"
METADATA_PUBLISH_OPERATION_COLUMN_NAME: str = "operation"
METADATA_PUBLISH_PREVIOUS_DEPLOYMENT_COLUMN_NAME: str = "previous_deployment_id"
METADATA_SCHEMA_VERSIONS_TABLE_NAME: str = "_streambuild_schema_versions"
METADATA_DIRECT_FINGERPRINTS_TABLE_NAME: str = "_streambuild_direct_fingerprints"
METADATA_INVOCATIONS_TABLE_NAME: str = "_streambuild_invocations"
METADATA_NODE_RESULTS_TABLE_NAME: str = "_streambuild_node_results"
METADATA_RUN_EVENTS_TABLE_NAME: str = "_streambuild_run_events"
METADATA_AUDIT_SCHEDULE_CLAIMS_TABLE_NAME: str = "_streambuild_audit_schedule_claims"
VIRTUAL_OBJECT_STATE_KIND_DEPLOYMENT: str = "deployment"
VIRTUAL_OBJECT_STATE_KIND_RECONCILE: str = "reconcile"
VIRTUAL_DEPLOYMENT_STATUS_INCOMPLETE: str = "incomplete"
REPLAY_VALUE_KIND_INTEGER: str = "integer"
REPLAY_VALUE_KIND_TIMESTAMP: str = "timestamp"
MANAGED_SOURCE_KIND_KAFKA: str = "kafka"
