"""Testing constants."""

MISSING_DIFF_TYPE: str = "missing"
UNEXPECTED_DIFF_TYPE: str = "unexpected"
ASSERTION_RESULT_LABEL_PREFIX: str = "assert "
COMPARISON_CASE_INDEX: int = 0
COMPARISON_DIFF_TYPE_INDEX: int = 1
COMPARISON_ROW_VALUES_INDEX: int = 2
COMPARISON_MULTIPLICITY_INDEX: int = 3
COMPARISON_ROW_LENGTH: int = 4
